### ISSUE TITLE
Can't import custoqr on Angular V8

### ISSUE THREAD

**Issue by Yop-Yop** [Intosoft/qrcode#28]
Hi ! 
I've got a problem importing this library on Angular environment : 

ERROR in node_modules/@intosoft/custoqr/dist/index.d.ts:5:1 - error TS1128: Declaration or statement expected.

5 export type { Config, WifiEncryption, BodyShape, EyeFrameShape, EyeballShape };

node_modules/@intosoft/custoqr/dist/index.d.ts:5:13 - error TS1005: ';' expected.

5 export type { Config, WifiEncryption, BodyShape, EyeFrameShape, EyeballShape };

ERROR in ./src/app/modules/directives/partials/qrCode/qrCode.partial.ts
Module not found: Error: Can't resolve '@intosoft/custoqr/dist/generateSVGString' in 'W:\www\...'
i ｢wdm｣: Failed to compile.

It seems that index.d.ts is not correct on Angular. Do you have a solution ? 
Thanks

**Comment by sakul-budhathoki** [comment]
@Yop-Yop  fixed it on version `0.0.7`

**Comment by sakul-budhathoki** [comment]
fixed by #29
