### ISSUE TITLE
Error in NodeJS 

### ISSUE THREAD

**Issue by Cronoz1994** [Intosoft/qrcode#31]
An error appears when using the library in NodeJs, in the index.js file related to the **window** object.

I solved it as follows:
`if (typeof window !== 'undefined') {...}`

Take it into account for the next update @sakul-budhathoki.
Thaks.

**Comment by sakul-budhathoki** [comment]
@Cronoz1994  Thanks for the report.
Published the fix on version `0.0.8` on npm.
