### ISSUE TITLE
Problem with NodeJS

### ISSUE THREAD

**Issue by Yop-Yop** [Intosoft/qrcode#33]
Hi ! 
Very nice lib with very nice QRcodes render ! 
I love your lib, thank you very much to share your work.

I have also a problem with NodeJs : 
For an old project on Node V 13.7.0, when i include your lib : 

const custoqr  = require("@intosoft/custoqr");

I get an error : 
```
\node_modules\@intosoft\custoqr\dist\index.js:4
`,n=0;return r.forEach(s=>{let i=s?.percentage?s.percentage:`${n}%`;e+=`  <stop offset="${i}" style="stop-color:${s?.color};stop-opacity:1" />
                                   ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:1067:16)
    at Module._compile (internal/modules/cjs/loader.js:1115:27)
```

I tested it with NodeJS V 18.10.0 and another error occured : 
```
node_modules\@intosoft\custoqr\dist\index.js:58
  </svg>`};var vt={generateSVGString:I,generateContentString:A};window&&(window.custoqr={generateSVGString:I,generateContentString:A});0&&(module.exports={generateContentString,generateSVGString});
                                                                ^

ReferenceError: window is not defined
```

Can you help me with it ? 
If it could run on nodeJS 13.7.0, it would be perfect !
Many Thanks !

**Comment by sakul-budhathoki** [comment]
@Yop-Yop 
Can you install version `0.0.8`?

I just tested it on Node.js v13.14.0 and v18.19.0; it's working fine for me.

Thanks.
